### ISSUE TITLE
windows: position of windows when the Taskbar is on the right side

### ISSUE THREAD

**Issue by ruettenm** [codecentric/merge-request-notifier#105]
currently it looks like this

![image](https://user-images.githubusercontent.com/2926623/74577773-3e29cb00-4f91-11ea-9ea6-275aba5624e4.png)

**Comment by fkockmeyer** [comment]
Das Peoblem ist hier, dass das Icon gant links am Bildschirmrand ist und die Positionierung direkt neben dem Icon gemacht wird. Also nicht in Relation zur gesamten Taskleiste. Es kommt also stark darsuf an wo das Icon angedockt ist. Man müsste also eigentlich relativ zur Taskleiste positionieren, falls möglich.

**Comment by ruettenm** [comment]
Okay. Ich schaue heute Abend mal. Ich meine Carsten hatte das Problem auch unter Linux und dort gelöst.

Beim Mac gibt es die Leiste zum Glück nur oben 😊

**Comment by ruettenm** [comment]
@fkockmeyer Ich habe mir das Problem heute endlich noch einmal vorgenommen und eine Library gefunden, die die Positionierung unter Windows korrekt hin bekommt 🎉 

**Rechts**
![image](https://user-images.githubusercontent.com/2926623/92272582-188eef80-eeea-11ea-80fe-ea418897bba3.png)

**Oben**
![image](https://user-images.githubusercontent.com/2926623/92272592-1e84d080-eeea-11ea-85fe-8168a885123f.png)

**Unten**
![image](https://user-images.githubusercontent.com/2926623/92272606-23e21b00-eeea-11ea-96c8-2ad05654717a.png)

**Links**
![image](https://user-images.githubusercontent.com/2926623/92272617-28a6cf00-eeea-11ea-8078-67cc04516f04.png)

Der Bugfix ist in folgendem Release enthalten:
https://github.com/codecentric/merge-request-notifier/releases/tag/v1.8.4

Passt das jetzt auch so bei dir?
