### ISSUE TITLE
Window hidden behind Windows vertical taskbar

### ISSUE THREAD

**Issue by matueranet** [codecentric/merge-request-notifier#148]
Hi, first of all, thanks for a great tool! I just discovered it, and it is exactly what I need to get a better overview of my Merge Requests.

I use it under Windows, and my setup deviates a little from the standard. The taskbar is configured vertically instead of horizontally, and because of this the left part of the window is not correctly aligned. See the screenshot below.

Is this something you can look into / fix?

![image](https://user-images.githubusercontent.com/2101780/91831051-dd6b9280-ec43-11ea-9043-7de1f96fdf4e.png)

**Comment by ruettenm** [comment]
Hi 👋 

Thanks for the feedback 👍  I happy that also other people are using my tool ;-) 

The same issue was also reported here: #105 

I'll try to fix it in the next days.

btw... in the settings you can change the try icon to use a "dark theme style" (white icon).

**Comment by ruettenm** [comment]
@matueranet I found a solution and tested it successfully with all four possible taskbar positions.

![win-right](https://user-images.githubusercontent.com/2926623/92264994-710cbf80-eedf-11ea-8090-1917f2720653.JPG)

![win-top](https://user-images.githubusercontent.com/2926623/92264996-71a55600-eedf-11ea-8e81-ad9cd16862b5.JPG)

![win-bottom](https://user-images.githubusercontent.com/2926623/92264998-723dec80-eedf-11ea-90f2-be372a7db029.JPG)

![win-left](https://user-images.githubusercontent.com/2926623/92264999-723dec80-eedf-11ea-807b-5e4e0ad981ae.JPG)


I'll create a new bugfix release.

**Comment by ruettenm** [comment]
The fix in included in this release:
https://github.com/codecentric/merge-request-notifier/releases/tag/v1.8.4

Please let me know if everything is fine :-)

**Comment by matueranet** [comment]
It works like a charm! Thanks a lot.
