### ISSUE TITLE
Reduce scope of scope of personal access token

### ISSUE THREAD

**Issue by rafaroca** [codecentric/merge-request-notifier#168]
Hi, first of all thanks for this great piece of software :)

I noticed that you suggest **api scope** for the Personal Access Token. Since the merge request notifier only needs read access, the text could be modified to **read_api**.

I could positively test that the read_api scope is enough.

**Comment by ruettenm** [comment]
Thanks for the hint. You are right. The notifier is only „reading“ the API ✔️
