### ISSUE TITLE
Incorrect update notification

### ISSUE THREAD

**Issue by stentrup** [codecentric/merge-request-notifier#67]
Update notification is shown although latest version is installed.

![image](https://user-images.githubusercontent.com/3942288/72239473-74b2a580-35e1-11ea-930c-d92702366f68.png)

**Comment by ruettenm** [comment]
Thanks for reporting. I saw the issue already on friday after the release of the latest version. 

Will be fixed later the day 🙏

**Comment by ruettenm** [comment]
Fixed in version **1.0.1**.
