### ISSUE TITLE
Move the "General" Tabs in front of the "Connection" tab

### ISSUE THREAD

**Issue by ruettenm** [codecentric/merge-request-notifier#77]
![image](https://user-images.githubusercontent.com/2926623/72900119-9e797400-3d27-11ea-88b3-a3cb05f50074.png)

If the user does not have a "connection configuration" yet, we should set the initial active tab to the "Connection" tab.

**Comment by tagirova** [comment]
https://github.com/codecentric/merge-request-notifier/pull/79/files
